# Generated by Django 5.2.9 on 2026-04-03 14:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('operateur', 'Opérateur')], default='operateur', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OuvertureProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne_production', models.CharField(max_length=100)),
                ('date_heure_ouverture', models.DateTimeField()),
                ('numero_lot', models.CharField(max_length=50)),
                ('numero_ordre_fabrication', models.CharField(max_length=100)),
                ('nom_produit', models.CharField(max_length=150)),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=10)),
                ('shift', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvertures', to='gestion_stock.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('lot_code1', models.CharField(max_length=50)),
                ('lot_code2', models.CharField(max_length=50)),
                ('lot_code3', models.CharField(max_length=50)),
                ('lot_code4', models.CharField(blank=True, default='', max_length=50)),
                ('lot_code5', models.CharField(blank=True, default='', max_length=50)),
                ('lot_code6', models.CharField(blank=True, default='', max_length=50)),
                ('lot_code7', models.CharField(blank=True, default='', max_length=50)),
                ('lot_code8', models.CharField(blank=True, default='', max_length=50)),
                ('lot_code9', models.CharField(blank=True, default='', max_length=50)),
                ('lot_code10', models.CharField(blank=True, default='', max_length=50)),
                ('date_expiration', models.DateField()),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.fournisseur')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='gestion_stock.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SortieStockProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('numero_lot', models.CharField(max_length=50)),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='gestion_stock.profile')),
            ],
        ),
    ]
