# Generated by Django 5.2.9 on 2026-04-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0001_initial'),
    ]

    operations = [
    ]
