# Generated by Django 5.2.9 on 2026-04-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0002_auto_20260403_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_operateur',
            field=models.CharField(choices=[('admin', 'Admin'), ('operateur', 'Opérateur')], max_length=20, default='operateur'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),

    ]
