# Generated by Django 5.2.9 on 2026-04-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0003_add_profile_type_operateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
