# Generated by Django 5.2.9 on 2026-04-07 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0005_alter_fournisseur_id_alter_ouvertureproduction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='date_reception',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
