# Generated by Django 6.0.2 on 2026-04-16 16:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0006_alter_reception_date_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='lot_quantite1',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite10',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite2',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite3',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite4',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite5',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite6',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite7',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite8',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reception',
            name='lot_quantite9',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='reception',
            name='date_reception',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
