# Generated by Django 6.0.2 on 2026-04-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0007_add_per_lot_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvertureproduction',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
