# Generated by Django 6.0.2 on 2026-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0008_ouverture_quantite_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvertureproduction',
            name='numero_ordre_fabrication',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
